package swing;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Americo
 */
public class Gui_swing extends javax.swing.JFrame {

    /** Creates new form Gui_swing */
    
    //ATTRIBUTES
    private static String consoleText = "";
    
    //CONSTRUCTOR
    public Gui_swing() {
        initComponents();
        setSize(1200, 800);
        setLocation(150, 150);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbcreate_issue = new javax.swing.JButton();
        jbupload_docs = new javax.swing.JButton();
        jbcreate_subtasks = new javax.swing.JButton();
        jbcreate_all = new javax.swing.JButton();
        update_console = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaconsole = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jbcreate_issue.setBackground(new java.awt.Color(255, 255, 255));
        jbcreate_issue.setText("Create Issue");
        jbcreate_issue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcreate_issueActionPerformed(evt);
            }
        });

        jbupload_docs.setBackground(new java.awt.Color(255, 255, 255));
        jbupload_docs.setText("Upload Docs");
        jbupload_docs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbupload_docsActionPerformed(evt);
            }
        });

        jbcreate_subtasks.setBackground(new java.awt.Color(255, 255, 255));
        jbcreate_subtasks.setText("Create SubTasks");
        jbcreate_subtasks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcreate_subtasksActionPerformed(evt);
            }
        });

        jbcreate_all.setBackground(new java.awt.Color(255, 255, 255));
        jbcreate_all.setText("Create ALL");
        jbcreate_all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcreate_allActionPerformed(evt);
            }
        });

        update_console.setBackground(new java.awt.Color(255, 255, 255));
        update_console.setText("Update Console");
        update_console.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_consoleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jbcreate_subtasks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbcreate_all, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbupload_docs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbcreate_issue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(update_console, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jbcreate_issue)
                .addGap(40, 40, 40)
                .addComponent(jbupload_docs)
                .addGap(37, 37, 37)
                .addComponent(jbcreate_subtasks)
                .addGap(41, 41, 41)
                .addComponent(jbcreate_all)
                .addGap(36, 36, 36)
                .addComponent(update_console)
                .addContainerGap(234, Short.MAX_VALUE))
        );

        jtaconsole.setColumns(20);
        jtaconsole.setRows(5);
        jtaconsole.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jtaconsoleInputMethodTextChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jtaconsole);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jbcreate_issueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcreate_issueActionPerformed
        System.out.println("create issue");
        jtaconsole.setText("Adding text to field");
    }//GEN-LAST:event_jbcreate_issueActionPerformed

    private void jbupload_docsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbupload_docsActionPerformed
        System.out.println("upload docs");
    }//GEN-LAST:event_jbupload_docsActionPerformed

    private void jbcreate_subtasksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcreate_subtasksActionPerformed
        System.out.println("create subtasks");
    }//GEN-LAST:event_jbcreate_subtasksActionPerformed

    private void jbcreate_allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcreate_allActionPerformed
        System.out.println("create all");
       
    }//GEN-LAST:event_jbcreate_allActionPerformed

    private void jtaconsoleInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jtaconsoleInputMethodTextChanged
        System.out.println("Adding text to field");
    }//GEN-LAST:event_jtaconsoleInputMethodTextChanged

    private void update_consoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_consoleActionPerformed
        System.out.println("update console");
        consoleText += "Adding text to field +++\n";
        jtaconsole.setText(consoleText);    }//GEN-LAST:event_update_consoleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui_swing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui_swing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui_swing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui_swing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui_swing().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbcreate_all;
    private javax.swing.JButton jbcreate_issue;
    private javax.swing.JButton jbcreate_subtasks;
    private javax.swing.JButton jbupload_docs;
    private javax.swing.JTextArea jtaconsole;
    private javax.swing.JButton update_console;
    // End of variables declaration//GEN-END:variables
}
